#!/usr/bin/env python
"""release_notes.py — RELEASE_NOTES_<release_id>.md generated from two unpacked packages (MATURITY_PLAN §2 "Release diff report").

    python -m catalog.release.release_notes --prev data/inputs/data_package --new build/package --out build/package/RELEASE_NOTES_R2026.1.md

Deterministic: every date comes from VERSION.json (never wall-clock); every number is computed from the two packages.
Sections: studies/samples added & removed · per-field coverage on catalog_scope before/after (RECOMPUTED from
sample_metadata_wide; field list from field_coverage_summary.csv) · verdict flips (universe_studies_all.triage_verdict)
· findings applied (value_history rows present in NEW but not in PREV, by change_stage) · Sandpiper snapshot ·
gold metrics before/after (extraction_gold_eval_hires.csv) · schema changes (files + columns) · bitemporal summary
(bitemporal_log.json) · token cost (docs/CYCLE_LOG.md row for this cycle, else "not recorded").
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import pandas as pd
import pyarrow.parquet as pq
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
CONFIG_DIR = os.environ.get("CATALOG_CONFIG_DIR", os.path.join(REPO, "config"))
TABLE_EXT = (".parquet", ".csv", ".csv.gz", ".json", ".md", ".ipynb")


def _version(pkg: str) -> dict:
    p = os.path.join(pkg, "VERSION.json")
    return json.load(open(p)) if os.path.exists(p) else {}


def _cols(path: str) -> list[str]:
    if path.endswith(".parquet"):
        return list(pq.ParquetFile(path).schema_arrow.names)
    if path.endswith(".csv"):
        return list(pd.read_csv(path, nrows=0).columns)
    if path.endswith(".csv.gz"):
        return list(pd.read_csv(path, nrows=0, compression="gzip").columns)
    return []


def _files(pkg: str) -> list[str]:
    return sorted(f for f in os.listdir(pkg) if f.endswith(TABLE_EXT) and os.path.isfile(os.path.join(pkg, f)))


def _fmt(n) -> str:
    return f"{n:,}" if isinstance(n, (int,)) or (isinstance(n, float) and n.is_integer()) else str(n)


def _md_table(rows: list[list], header: list[str]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def release_id_for(cfg: dict, package_version: str, vj: dict) -> str:
    if vj.get("release_id"):
        return vj["release_id"]
    for r in cfg["releases"]:
        if r["package_version"] == package_version:
            return r["release_id"]
    for h in cfg["history"]:
        if h["package_version"] == package_version:
            return h["id"]
    return package_version


def coverage_catalog_scope(pkg: str) -> pd.Series | None:
    fcs = os.path.join(pkg, "field_coverage_summary.csv")
    smw = os.path.join(pkg, "sample_metadata_wide.parquet")
    if not (os.path.exists(fcs) and os.path.exists(smw)):
        return None
    fields = [f for f in pd.read_csv(fcs)["field"].astype(str) if f in _cols(smw)]
    w = pd.read_parquet(smw, columns=fields + ["catalog_scope"])
    w = w[w["catalog_scope"].fillna(False).astype(bool)]
    return pd.Series({f: int(w[f].notna().sum()) for f in fields}, name="n").rename_axis("field"), len(w)


def cycle_log_line(release_id: str, package_version: str, cycle_log: str) -> str:
    if not os.path.exists(cycle_log):
        return "not recorded"
    for line in open(cycle_log, encoding="utf-8"):
        if line.startswith("|") and (release_id in line or f"| {package_version} " in line or f" {package_version} |" in line):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) >= 6 and not cells[0].startswith("-"):
                return f"{cells[5]} (docs/CYCLE_LOG.md row `{cells[0]}`)"
    return "not recorded"


def build(prev: str, new: str, cfg: dict | None = None, cycle_log: str | None = None) -> str:
    cfg = cfg or yaml.safe_load(open(os.path.join(CONFIG_DIR, "releases.yaml"), encoding="utf-8"))
    vp, vn = _version(prev), _version(new)
    pv_prev, pv_new = vp.get("package_version", "?"), vn.get("package_version", "?")
    rid = release_id_for(cfg, pv_new, vn)
    rid_prev = release_id_for(cfg, pv_prev, vp)
    L = [f"# Release notes — {rid} (data package {pv_new}, {vn.get('build_date', 'date unknown')})", "",
         f"Generated by `catalog.release.release_notes` from package {pv_prev} ({rid_prev}, {vp.get('build_date', '?')}) → {pv_new}. "
         f"Every number below is computed from the two packages; dates come from VERSION.json.", ""]

    # ---- studies / samples
    def keys(pkg, f, k):
        p = os.path.join(pkg, f)
        return set(pd.read_parquet(p, columns=[k])[k].astype(str)) if os.path.exists(p) else set()
    sp, sn = keys(prev, "study_metadata_wide.parquet", "study_accession"), keys(new, "study_metadata_wide.parquet", "study_accession")
    mp, mn = keys(prev, "sample_metadata_wide.parquet", "sample_key"), keys(new, "sample_metadata_wide.parquet", "sample_key")
    L += ["## Studies and samples", "",
          _md_table([["included studies", _fmt(len(sp)), _fmt(len(sn)), _fmt(len(sn - sp)), _fmt(len(sp - sn))],
                     ["catalog samples", _fmt(len(mp)), _fmt(len(mn)), _fmt(len(mn - mp)), _fmt(len(mp - mn))]],
                    ["entity", pv_prev, pv_new, "added", "removed"]), ""]
    if sn - sp:
        L += ["New included studies: " + ", ".join(sorted(sn - sp)[:100]) + (" …" if len(sn - sp) > 100 else ""), ""]
    if sp - sn:
        L += ["Removed included studies: " + ", ".join(sorted(sp - sn)[:100]) + (" …" if len(sp - sn) > 100 else ""), ""]

    # ---- coverage
    cp, cn = coverage_catalog_scope(prev), coverage_catalog_scope(new)
    L += ["## Per-field coverage on `catalog_scope`", ""]
    if cp and cn:
        (sp_, np_), (sn_, nn_) = cp, cn
        rows = []
        for f in sn_.index:
            a, b = int(sp_.get(f, 0)), int(sn_[f])
            rows.append([f"`{f}`", _fmt(a), f"{100 * a / np_:.1f}%" if np_ else "—", _fmt(b), f"{100 * b / nn_:.1f}%" if nn_ else "—", f"{b - a:+,}"])
        L += [f"Recomputed from `sample_metadata_wide` (non-null values among catalog_scope rows: {np_:,} → {nn_:,}); field list from `field_coverage_summary.csv`.", "",
              _md_table(rows, ["field", f"n {pv_prev}", "cov", f"n {pv_new}", "cov", "Δ n"]), ""]
    else:
        L += ["not computable (field_coverage_summary.csv or sample_metadata_wide.parquet missing)", ""]

    # ---- verdict flips
    L += ["## Triage verdict flips (`universe_studies_all.triage_verdict`)", ""]
    up, un = os.path.join(prev, "universe_studies_all.parquet"), os.path.join(new, "universe_studies_all.parquet")
    if os.path.exists(up) and os.path.exists(un):
        a = pd.read_parquet(up, columns=["study_accession", "triage_verdict"]).astype(str).set_index("study_accession")["triage_verdict"]
        b = pd.read_parquet(un, columns=["study_accession", "triage_verdict"]).astype(str).set_index("study_accession")["triage_verdict"]
        j = pd.concat([a.rename("prev"), b.rename("new")], axis=1)
        both = j["prev"].notna() & j["new"].notna()
        n_new_studies, n_gone = int((~j["prev"].notna()).sum()), int((~j["new"].notna()).sum())
        flips = j[(j["prev"] != j["new"])].fillna("(absent)").sort_index()  # includes new/removed studies, labelled (absent)
        L += [f"Universe {len(a):,} → {len(b):,} studies; verdict distribution {pv_new}: " +
              ", ".join(f"{k} {v:,}" for k, v in b.value_counts().sort_index().items()) + f". **{int((both & (j['prev'] != j['new'])).sum()):,} flips** among studies present in both packages; {n_new_studies:,} studies new to the universe, {n_gone:,} removed.", ""]
        if len(flips):
            L += [_md_table([[i, r["prev"], r["new"]] for i, r in flips.head(200).iterrows()], ["study", pv_prev, pv_new]), ""]
    else:
        L += ["not computable", ""]

    # ---- findings applied
    L += ["## Findings applied in this release (`value_history` rows new since the previous package)", ""]
    hp, hn = os.path.join(prev, "value_history.parquet"), os.path.join(new, "value_history.parquet")
    if os.path.exists(hp) and os.path.exists(hn):
        a, b = pd.read_parquet(hp), pd.read_parquet(hn)
        cols = [c for c in b.columns if c in a.columns]
        m = b[cols].astype(str).merge(a[cols].astype(str).drop_duplicates(), how="left", indicator=True)
        newrows = b[(m["_merge"] == "left_only").to_numpy()]
        L += [f"value_history {len(a):,} → {len(b):,} rows; **{len(newrows):,} new rows**" +
              (" by change_stage: " + ", ".join(f"`{k}` {v:,}" for k, v in newrows["change_stage"].value_counts().sort_index().items()) if len(newrows) else "") + ".", ""]
        appl = os.path.join(new, "APPLY_FINDINGS_DIFF.md")
        if os.path.exists(appl):
            L += ["`APPLY_FINDINGS_DIFF.md` is shipped in the package.", ""]
    else:
        L += ["not computable", ""]

    # ---- Sandpiper
    L += ["## Sandpiper snapshot", ""]
    def sp_ver(pkg):
        p = os.path.join(pkg, "sandpiper_sample_summary.parquet")
        if not os.path.exists(p):
            return "—", "—", 0
        d = pd.read_parquet(p, columns=["sandpiper_version", "zenodo_record"])
        return ";".join(sorted(d["sandpiper_version"].dropna().astype(str).unique())), ";".join(sorted(d["zenodo_record"].dropna().astype(str).unique())), len(d)
    (v1, z1, n1), (v2, z2, n2) = sp_ver(prev), sp_ver(new)
    L += [_md_table([["sandpiper_version", v1, v2], ["zenodo_record", z1, z2], ["profiled samples", _fmt(n1), _fmt(n2)]], ["", pv_prev, pv_new]), ""]

    # ---- gold
    L += ["## Gold metrics (`extraction_gold_eval_hires.csv`, curatedMetagenomicData hi-res set)", ""]
    gp, gn = os.path.join(prev, "extraction_gold_eval_hires.csv"), os.path.join(new, "extraction_gold_eval_hires.csv")
    if os.path.exists(gp) and os.path.exists(gn):
        a, b = pd.read_csv(gp, index_col=0), pd.read_csv(gn, index_col=0)
        rows = []
        for f in b.index:
            ra, rb = (a.loc[f] if f in a.index else None), b.loc[f]
            rows.append([f"`{f}`", _fmt(int(rb["gold_n"])) if pd.notna(rb.get("gold_n")) else "—"] +
                        [f"{ra[m]:.3f}" if ra is not None and pd.notna(ra.get(m)) else "—" for m in ("coverage", "precision", "recall")] +
                        [f"{rb[m]:.3f}" if pd.notna(rb.get(m)) else "—" for m in ("coverage", "precision", "recall")])
        L += [_md_table(rows, ["field", "gold n", f"cov {pv_prev}", f"prec {pv_prev}", f"rec {pv_prev}", f"cov {pv_new}", f"prec {pv_new}", f"rec {pv_new}"]), ""]
    else:
        L += ["not computable", ""]

    # ---- schema changes
    L += ["## Schema changes", ""]
    fp, fn_ = _files(prev), _files(new)
    added_f, removed_f = sorted(set(fn_) - set(fp)), sorted(set(fp) - set(fn_))
    L += ["New files: " + (", ".join(f"`{f}`" for f in added_f) if added_f else "none"),
          "Removed files: " + (", ".join(f"`{f}`" for f in removed_f) if removed_f else "none"), ""]
    col_rows = []
    for f in sorted(set(fp) & set(fn_)):
        if not f.endswith((".parquet", ".csv", ".csv.gz")):
            continue
        a, b = _cols(os.path.join(prev, f)), _cols(os.path.join(new, f))
        if a != b:
            col_rows.append([f"`{f}`", ", ".join(f"`{c}`" for c in b if c not in a) or "—", ", ".join(f"`{c}`" for c in a if c not in b) or "—"])
    L += [_md_table(col_rows, ["table", "columns added", "columns removed"]) if col_rows else "No column changes in tables present in both packages.", ""]
    vsn = {k: v for k, v in vn.items() if k in ("release_id", "previous_release_id", "release_tag", "package_version", "schema_version")}
    if vsn:
        L += ["VERSION.json: " + ", ".join(f"`{k}`={v}" for k, v in sorted(vsn.items())), ""]

    # ---- bitemporal
    bl = os.path.join(new, "bitemporal_log.json")
    if os.path.exists(bl):
        log = json.load(open(bl))
        d = log.get("sample_determinations", {})
        L += ["## Bitemporal columns (`release_added` / `release_retired` / `package_added`)", "",
              f"`sample_determinations_all.parquet`: {d.get('n_current', 0):,} current + {d.get('n_retired', 0):,} retired rows "
              f"({d.get('n_retired_gone_this_release', 0):,} retired in {rid}). Rule for retired rows: {d.get('retired_rule', '?')}.", "",
              _md_table([[k, _fmt(v)] for k, v in sorted(d.get("release_added_counts", {}).items())], ["release_added (current determinations)", "rows"]), "",
              _md_table([[k, _fmt(v)] for k, v in sorted(d.get("release_retired_counts", {}).items())], ["release_retired (retired determinations)", "rows"]), "",
              "Pre-1.3.0 values of `release_added` are reconstructed from `value_history.change_stage` / `src_track` — see `docs/RELEASES.md` §3 for exactness per row class.", ""]

    # ---- token cost
    L += ["## Token cost", "", "LLM tokens this cycle: " + cycle_log_line(rid, pv_new, cycle_log or os.path.join(REPO, "docs", "CYCLE_LOG.md")), ""]
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--prev", required=True, help="unpacked previous package dir")
    ap.add_argument("--new", required=True, help="unpacked new package dir")
    ap.add_argument("--out", required=True, help="markdown path (RELEASE_NOTES_<release_id>.md)")
    ap.add_argument("--cycle-log", default=None)
    a = ap.parse_args(argv)
    md = build(a.prev, a.new, cycle_log=a.cycle_log)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w", encoding="utf-8").write(md)
    print(json.dumps({"out": a.out, "bytes": len(md.encode())}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
